// <auto-generated />
using System;
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(UEMSContext))]
    [Migration("20260713223929_lang_comp_constraint_and_enum")]
    partial class lang_comp_constraint_and_enum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<bool>("Accommodation")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("AccommodationFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("AccommodationTo")
                        .HasColumnType("date");

                    b.Property<bool>("BulgarianCourse")
                        .HasColumnType("bit");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MobilityId")
                        .HasColumnType("int")
                        .HasColumnName("MobilityID");

                    b.Property<string>("MotivationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhotoId")
                        .HasColumnType("int")
                        .HasColumnName("PhotoID");

                    b.Property<int>("SendingFacultyId")
                        .HasColumnType("int")
                        .HasColumnName("SendingFacultyID");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<DateOnly>("StudyFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StudyTo")
                        .HasColumnType("date");

                    b.Property<int>("TermId")
                        .HasColumnType("int")
                        .HasColumnName("TermID");

                    b.HasKey("ApplicationId");

                    b.HasIndex("MobilityId");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.HasIndex("SendingFacultyId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TermId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("API.Models.ApplicationFile", b =>
                {
                    b.Property<int>("ApplicationFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ApplicationFileID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationFileId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentID");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("ApplicationFileId");

                    b.HasIndex(new[] { "ApplicationId" }, "UQ_ApplicationFile_ApplicationID")
                        .IsUnique();

                    b.HasIndex(new[] { "DocumentId" }, "UQ_ApplicationFile_DocumentID")
                        .IsUnique()
                        .HasFilter("[DocumentID] IS NOT NULL");

                    b.ToTable("ApplicationFile", (string)null);
                });

            modelBuilder.Entity("API.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ContactID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("API.Models.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DisciplineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisciplineId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("FacultyID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DisciplineId");

                    b.HasIndex("FacultyId");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("API.Models.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FacultyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyId"));

                    b.Property<int?>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("ContactID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("int")
                        .HasColumnName("UniversityID");

                    b.HasKey("FacultyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("API.Models.FacultyMobility", b =>
                {
                    b.Property<int>("MobilityId")
                        .HasColumnType("int")
                        .HasColumnName("MobilityID");

                    b.Property<int>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("ContactID");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("DisciplineID");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("FacultyID");

                    b.HasKey("MobilityId");

                    b.HasIndex("ContactId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("FacultyId");

                    b.ToTable("FacultyMobilities", t =>
                        {
                            t.HasTrigger("TR_FacultyMobilities_TypeGuard");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("API.Models.File", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FileID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FileContentId")
                        .HasColumnType("int")
                        .HasColumnName("FileContentID");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.HasKey("FileId");

                    b.HasIndex(new[] { "FileContentId" }, "UQ_Files_FileContentID")
                        .IsUnique();

                    b.ToTable("Files");
                });

            modelBuilder.Entity("API.Models.FileContent", b =>
                {
                    b.Property<int>("FileContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FileContentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileContentId"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("FileContent");

                    b.HasKey("FileContentId");

                    b.ToTable("FileContents");
                });

            modelBuilder.Entity("API.Models.Firm", b =>
                {
                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FirmID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FirmId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("ContactID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("FirmId");

                    b.HasIndex("ContactId");

                    b.ToTable("Firms");
                });

            modelBuilder.Entity("API.Models.FirmMobility", b =>
                {
                    b.Property<int>("MobilityId")
                        .HasColumnType("int")
                        .HasColumnName("MobilityID");

                    b.Property<int>("FirmId")
                        .HasColumnType("int")
                        .HasColumnName("FirmID");

                    b.HasKey("MobilityId");

                    b.HasIndex("FirmId");

                    b.ToTable("FirmMobilities", t =>
                        {
                            t.HasTrigger("TR_FirmMobilities_TypeGuard");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("API.Models.HashedToken", b =>
                {
                    b.Property<int>("HashedTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HashedTokenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HashedTokenId"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("HashedTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("HashedTokens");
                });

            modelBuilder.Entity("API.Models.LanguageCompetency", b =>
                {
                    b.Property<int>("LanguageCompetencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LanguageCompetencyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageCompetencyId"));

                    b.Property<bool>("CanFollowLectures")
                        .HasColumnType("bit");

                    b.Property<bool>("CanFollowLecturesWithLessons")
                        .HasColumnType("bit");

                    b.Property<int?>("CertificateId")
                        .HasColumnType("int")
                        .HasColumnName("CertificateID");

                    b.Property<string>("CompetencyLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("LanguageCompetencyId");

                    b.HasIndex("CertificateId")
                        .IsUnique()
                        .HasFilter("CertificateId IS NOT NULL");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "CertificateId" }, "UQ_LanguageCompetencies_CertificateID")
                        .IsUnique()
                        .HasFilter("[CertificateID] IS NOT NULL");

                    b.ToTable("LanguageCompetencies");
                });

            modelBuilder.Entity("API.Models.Mobility", b =>
                {
                    b.Property<int>("MobilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MobilityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MobilityId"));

                    b.Property<string>("MobilityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MobilityId");

                    b.ToTable("Mobilities");
                });

            modelBuilder.Entity("API.Models.RelDisciplineSubject", b =>
                {
                    b.Property<int>("DisciplineSubjectsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DisciplineSubjectsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisciplineSubjectsId"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("DisciplineID");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    b.HasKey("DisciplineSubjectsId");

                    b.HasIndex("SubjectId");

                    b.HasIndex(new[] { "DisciplineId", "SubjectId" }, "UQ_relDisciplineSubjects")
                        .IsUnique();

                    b.ToTable("relDisciplineSubjects", (string)null);
                });

            modelBuilder.Entity("API.Models.RelFacultyMobilitiesSubject", b =>
                {
                    b.Property<int>("RelFacultyMobilitiesSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("relFacultyMobilitiesSubjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelFacultyMobilitiesSubjectId"));

                    b.Property<int>("FacultyMobilityId")
                        .HasColumnType("int")
                        .HasColumnName("FacultyMobilityID");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    b.HasKey("RelFacultyMobilitiesSubjectId");

                    b.HasIndex("SubjectId");

                    b.HasIndex(new[] { "FacultyMobilityId", "SubjectId" }, "UQ_relFacMobSubj")
                        .IsUnique();

                    b.ToTable("relFacultyMobilitiesSubjects", (string)null);
                });

            modelBuilder.Entity("API.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("StudentId");

                    b.HasIndex(new[] { "UserId" }, "UQ_Students_UserID")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("API.Models.Study", b =>
                {
                    b.Property<int>("StudyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudyId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudyDuration")
                        .HasColumnType("int");

                    b.HasKey("StudyId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("API.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("FacultyID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SubjectId");

                    b.HasIndex("FacultyId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("API.Models.Term", b =>
                {
                    b.Property<int>("TermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TermID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TermId"));

                    b.Property<DateOnly>("ApplicationDeadline")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("TermId");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("API.Models.University", b =>
                {
                    b.Property<int>("UniversityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UniversityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UniversityId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UniversityId");

                    b.HasIndex(new[] { "Code" }, "UQ_Universities_Code")
                        .IsUnique();

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Models.WorkExperience", b =>
                {
                    b.Property<int>("WorkExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WorkExperienceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkExperienceId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExperienceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.HasKey("WorkExperienceId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("WorkExperiences");
                });

            modelBuilder.Entity("API.Models.Application", b =>
                {
                    b.HasOne("API.Models.Mobility", "Mobility")
                        .WithMany("Applications")
                        .HasForeignKey("MobilityId")
                        .IsRequired()
                        .HasConstraintName("FK_Applications_Mobilities");

                    b.HasOne("API.Models.File", "Photo")
                        .WithOne("Application")
                        .HasForeignKey("API.Models.Application", "PhotoId")
                        .IsRequired()
                        .HasConstraintName("FK_Applications_Files");

                    b.HasOne("API.Models.Faculty", "SendingFaculty")
                        .WithMany("Applications")
                        .HasForeignKey("SendingFacultyId")
                        .IsRequired()
                        .HasConstraintName("FK_Applications_SendingFaculty");

                    b.HasOne("API.Models.Student", "Student")
                        .WithMany("Applications")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Applications_Students");

                    b.HasOne("API.Models.Term", "Term")
                        .WithMany("Applications")
                        .HasForeignKey("TermId")
                        .IsRequired()
                        .HasConstraintName("FK_Applications_Terms");

                    b.Navigation("Mobility");

                    b.Navigation("Photo");

                    b.Navigation("SendingFaculty");

                    b.Navigation("Student");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("API.Models.ApplicationFile", b =>
                {
                    b.HasOne("API.Models.Application", "Application")
                        .WithOne("ApplicationFile")
                        .HasForeignKey("API.Models.ApplicationFile", "ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationFile_Applications");

                    b.HasOne("API.Models.File", "Document")
                        .WithOne("ApplicationFile")
                        .HasForeignKey("API.Models.ApplicationFile", "DocumentId")
                        .HasConstraintName("FK_ApplicationFile_Files");

                    b.Navigation("Application");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("API.Models.Discipline", b =>
                {
                    b.HasOne("API.Models.Faculty", "Faculty")
                        .WithMany("Disciplines")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK_Disciplines_Faculties");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("API.Models.Faculty", b =>
                {
                    b.HasOne("API.Models.Contact", "Contact")
                        .WithMany("Faculties")
                        .HasForeignKey("ContactId")
                        .HasConstraintName("FK_Faculties_Contacts");

                    b.HasOne("API.Models.University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityId")
                        .HasConstraintName("FK_Faculties_Universities");

                    b.Navigation("Contact");

                    b.Navigation("University");
                });

            modelBuilder.Entity("API.Models.FacultyMobility", b =>
                {
                    b.HasOne("API.Models.Contact", "Contact")
                        .WithMany("FacultyMobilities")
                        .HasForeignKey("ContactId")
                        .IsRequired()
                        .HasConstraintName("FK_FacultyMobilities_Contacts");

                    b.HasOne("API.Models.Discipline", "Discipline")
                        .WithMany("FacultyMobilities")
                        .HasForeignKey("DisciplineId")
                        .IsRequired()
                        .HasConstraintName("FK_FacultyMobilities_Disciplines");

                    b.HasOne("API.Models.Faculty", "Faculty")
                        .WithMany("FacultyMobilities")
                        .HasForeignKey("FacultyId")
                        .IsRequired()
                        .HasConstraintName("FK_FacultyMobilities_Faculties");

                    b.HasOne("API.Models.Mobility", "Mobility")
                        .WithOne("FacultyMobility")
                        .HasForeignKey("API.Models.FacultyMobility", "MobilityId")
                        .IsRequired()
                        .HasConstraintName("FK_FacultyMobilities_Mobilities");

                    b.Navigation("Contact");

                    b.Navigation("Discipline");

                    b.Navigation("Faculty");

                    b.Navigation("Mobility");
                });

            modelBuilder.Entity("API.Models.File", b =>
                {
                    b.HasOne("API.Models.FileContent", "FileContent")
                        .WithOne("File")
                        .HasForeignKey("API.Models.File", "FileContentId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_Files_FileContents");

                    b.Navigation("FileContent");
                });

            modelBuilder.Entity("API.Models.Firm", b =>
                {
                    b.HasOne("API.Models.Contact", "Contact")
                        .WithMany("Firms")
                        .HasForeignKey("ContactId")
                        .HasConstraintName("FK_Firms_Contacts");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("API.Models.FirmMobility", b =>
                {
                    b.HasOne("API.Models.Firm", "Firm")
                        .WithMany("FirmMobilities")
                        .HasForeignKey("FirmId")
                        .IsRequired()
                        .HasConstraintName("FK_FirmMobilities_Firms");

                    b.HasOne("API.Models.Mobility", "Mobility")
                        .WithOne("FirmMobility")
                        .HasForeignKey("API.Models.FirmMobility", "MobilityId")
                        .IsRequired()
                        .HasConstraintName("FK_FirmMobilities_Mobilities");

                    b.Navigation("Firm");

                    b.Navigation("Mobility");
                });

            modelBuilder.Entity("API.Models.HashedToken", b =>
                {
                    b.HasOne("API.Models.User", "User")
                        .WithMany("HashedTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_HashedTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.LanguageCompetency", b =>
                {
                    b.HasOne("API.Models.File", "Certificate")
                        .WithOne("LanguageCompetency")
                        .HasForeignKey("API.Models.LanguageCompetency", "CertificateId")
                        .HasConstraintName("FK_LanguageCompetencies_Files");

                    b.HasOne("API.Models.Student", "Student")
                        .WithMany("LanguageCompetencies")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_LanguageCompetencies_Students");

                    b.Navigation("Certificate");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("API.Models.RelDisciplineSubject", b =>
                {
                    b.HasOne("API.Models.Discipline", "Discipline")
                        .WithMany("RelDisciplineSubjects")
                        .HasForeignKey("DisciplineId")
                        .IsRequired()
                        .HasConstraintName("FK_relDisciplineSubjects_Disciplines");

                    b.HasOne("API.Models.Subject", "Subject")
                        .WithMany("RelDisciplineSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_relDisciplineSubjects_Subjects");

                    b.Navigation("Discipline");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("API.Models.RelFacultyMobilitiesSubject", b =>
                {
                    b.HasOne("API.Models.FacultyMobility", "FacultyMobility")
                        .WithMany("RelFacultyMobilitiesSubjects")
                        .HasForeignKey("FacultyMobilityId")
                        .IsRequired()
                        .HasConstraintName("FK_relFacMobSubj_FacultyMobilities");

                    b.HasOne("API.Models.Subject", "Subject")
                        .WithMany("RelFacultyMobilitiesSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_relFacMobSubj_Subjects");

                    b.Navigation("FacultyMobility");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("API.Models.Student", b =>
                {
                    b.HasOne("API.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("API.Models.Student", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Students_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Study", b =>
                {
                    b.HasOne("API.Models.Application", "Application")
                        .WithMany("Studies")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_Studies_Applications");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("API.Models.Subject", b =>
                {
                    b.HasOne("API.Models.Faculty", "Faculty")
                        .WithMany("Subjects")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK_Subjects_Faculties");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("API.Models.WorkExperience", b =>
                {
                    b.HasOne("API.Models.Application", "Application")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_WorkExperiences_Applications");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("API.Models.Application", b =>
                {
                    b.Navigation("ApplicationFile");

                    b.Navigation("Studies");

                    b.Navigation("WorkExperiences");
                });

            modelBuilder.Entity("API.Models.Contact", b =>
                {
                    b.Navigation("Faculties");

                    b.Navigation("FacultyMobilities");

                    b.Navigation("Firms");
                });

            modelBuilder.Entity("API.Models.Discipline", b =>
                {
                    b.Navigation("FacultyMobilities");

                    b.Navigation("RelDisciplineSubjects");
                });

            modelBuilder.Entity("API.Models.Faculty", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Disciplines");

                    b.Navigation("FacultyMobilities");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("API.Models.FacultyMobility", b =>
                {
                    b.Navigation("RelFacultyMobilitiesSubjects");
                });

            modelBuilder.Entity("API.Models.File", b =>
                {
                    b.Navigation("Application");

                    b.Navigation("ApplicationFile");

                    b.Navigation("LanguageCompetency");
                });

            modelBuilder.Entity("API.Models.FileContent", b =>
                {
                    b.Navigation("File");
                });

            modelBuilder.Entity("API.Models.Firm", b =>
                {
                    b.Navigation("FirmMobilities");
                });

            modelBuilder.Entity("API.Models.Mobility", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("FacultyMobility");

                    b.Navigation("FirmMobility");
                });

            modelBuilder.Entity("API.Models.Student", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("LanguageCompetencies");
                });

            modelBuilder.Entity("API.Models.Subject", b =>
                {
                    b.Navigation("RelDisciplineSubjects");

                    b.Navigation("RelFacultyMobilitiesSubjects");
                });

            modelBuilder.Entity("API.Models.Term", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("API.Models.University", b =>
                {
                    b.Navigation("Faculties");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Navigation("HashedTokens");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
