// <auto-generated />
using System;
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(UEMSContext))]
    partial class UEMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<bool>("Accommodation")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("AccommodationFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("AccommodationTo")
                        .HasColumnType("date");

                    b.Property<bool>("BulgarianCourse")
                        .HasColumnType("bit");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobilityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MotivationText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("PriorStudyAbroad")
                        .HasColumnType("bit");

                    b.Property<int?>("PriorStudyDuration")
                        .HasColumnType("int");

                    b.Property<int>("ReceivingInstitution")
                        .HasColumnType("int");

                    b.Property<int>("SendingInstitution")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<DateOnly>("StudyFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StudyTo")
                        .HasColumnType("date");

                    b.HasKey("ApplicationId");

                    b.HasIndex("ReceivingInstitution");

                    b.HasIndex("SendingInstitution");

                    b.HasIndex("StudentId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("API.Models.ApplicationDocument", b =>
                {
                    b.Property<int>("ApplicationDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ApplicationDocumentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationDocumentId"));

                    b.Property<byte[]>("Application")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ApplicationDocumentId");

                    b.HasIndex(new[] { "ApplicationId" }, "UQ_ApplicationDocuments_ApplicationID")
                        .IsUnique();

                    b.ToTable("ApplicationDocuments");
                });

            modelBuilder.Entity("API.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ContactID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int")
                        .HasColumnName("InstitutionID");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ContactId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("API.Models.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DisciplineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisciplineId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("FacultyID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DisciplineId");

                    b.HasIndex("FacultyId");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("API.Models.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FacultyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyId"));

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int")
                        .HasColumnName("InstitutionID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("FacultyId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("API.Models.HashedToken", b =>
                {
                    b.Property<int>("HashedTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HashedTokenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HashedTokenId"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("HashedTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("HashedTokens");
                });

            modelBuilder.Entity("API.Models.Institution", b =>
                {
                    b.Property<int>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InstitutionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstitutionId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("InstitutionId");

                    b.HasIndex(new[] { "Code" }, "UQ_Institutions_Code")
                        .IsUnique();

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("API.Models.LanguageCompetency", b =>
                {
                    b.Property<int>("LanguageCompetencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LanguageCompetencyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageCompetencyId"));

                    b.Property<bool>("CanFollowLectures")
                        .HasColumnType("bit");

                    b.Property<bool>("CanFollowLecturesWithLessons")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("LanguageCompetencyId");

                    b.HasIndex("StudentId");

                    b.ToTable("LanguageCompetencies");
                });

            modelBuilder.Entity("API.Models.RelDisciplineSubject", b =>
                {
                    b.Property<int>("DisciplineSubjectsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DisciplineSubjectsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisciplineSubjectsId"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("DisciplineID");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    b.HasKey("DisciplineSubjectsId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("SubjectId");

                    b.ToTable("relDisciplineSubjects", (string)null);
                });

            modelBuilder.Entity("API.Models.RelInstitutionApplication", b =>
                {
                    b.Property<int>("InstitutionApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InstitutionApplicationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstitutionApplicationId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<int>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("ContactID");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("DisciplineID");

                    b.HasKey("InstitutionApplicationId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ContactId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("relInstitutionApplications", (string)null);
                });

            modelBuilder.Entity("API.Models.RelInstitutionApplicationSubject", b =>
                {
                    b.Property<int>("InstitutionApplicationSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InstitutionApplicationSubjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstitutionApplicationSubjectId"));

                    b.Property<int>("InstitutionApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("InstitutionApplicationID");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    b.HasKey("InstitutionApplicationSubjectId");

                    b.HasIndex("InstitutionApplicationId");

                    b.HasIndex("SubjectId");

                    b.ToTable("relInstitutionApplicationSubjects", (string)null);
                });

            modelBuilder.Entity("API.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("StudentId");

                    b.HasIndex(new[] { "UserId" }, "UQ_Students_UserID")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("API.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int?>("InstitutionFacultyId")
                        .HasColumnType("int")
                        .HasColumnName("InstitutionFacultyID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SubjectId");

                    b.HasIndex("InstitutionFacultyId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Models.WorkExperience", b =>
                {
                    b.Property<int>("WorkExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WorkExperienceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkExperienceId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExperienceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.HasKey("WorkExperienceId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("WorkExperiences");
                });

            modelBuilder.Entity("API.Models.Application", b =>
                {
                    b.HasOne("API.Models.Institution", "ReceivingInstitutionNavigation")
                        .WithMany("ApplicationReceivingInstitutionNavigations")
                        .HasForeignKey("ReceivingInstitution")
                        .IsRequired()
                        .HasConstraintName("FK_Applications_ReceivingInstitution");

                    b.HasOne("API.Models.Institution", "SendingInstitutionNavigation")
                        .WithMany("ApplicationSendingInstitutionNavigations")
                        .HasForeignKey("SendingInstitution")
                        .IsRequired()
                        .HasConstraintName("FK_Applications_SendingInstitution");

                    b.HasOne("API.Models.Student", "Student")
                        .WithMany("Applications")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Applications_Students");

                    b.Navigation("ReceivingInstitutionNavigation");

                    b.Navigation("SendingInstitutionNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("API.Models.ApplicationDocument", b =>
                {
                    b.HasOne("API.Models.Application", "ApplicationNavigation")
                        .WithOne("ApplicationDocument")
                        .HasForeignKey("API.Models.ApplicationDocument", "ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationDocuments_Applications");

                    b.Navigation("ApplicationNavigation");
                });

            modelBuilder.Entity("API.Models.Contact", b =>
                {
                    b.HasOne("API.Models.Institution", "Institution")
                        .WithMany("Contacts")
                        .HasForeignKey("InstitutionId")
                        .HasConstraintName("FK_Contacts_Institutions");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("API.Models.Discipline", b =>
                {
                    b.HasOne("API.Models.Faculty", "Faculty")
                        .WithMany("Disciplines")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK_Disciplines_Faculties");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("API.Models.Faculty", b =>
                {
                    b.HasOne("API.Models.Institution", "Institution")
                        .WithMany("Faculties")
                        .HasForeignKey("InstitutionId")
                        .HasConstraintName("FK_Faculties_Institutions");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("API.Models.HashedToken", b =>
                {
                    b.HasOne("API.Models.User", "User")
                        .WithMany("HashedTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_HashedTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.LanguageCompetency", b =>
                {
                    b.HasOne("API.Models.Student", "Student")
                        .WithMany("LanguageCompetencies")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_LanguageCompetencies_Students");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("API.Models.RelDisciplineSubject", b =>
                {
                    b.HasOne("API.Models.Discipline", "Discipline")
                        .WithMany("RelDisciplineSubjects")
                        .HasForeignKey("DisciplineId")
                        .IsRequired()
                        .HasConstraintName("FK_relDiscSubj_Disciplines");

                    b.HasOne("API.Models.Subject", "Subject")
                        .WithMany("RelDisciplineSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_relDiscSubj_Subjects");

                    b.Navigation("Discipline");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("API.Models.RelInstitutionApplication", b =>
                {
                    b.HasOne("API.Models.Application", "Application")
                        .WithMany("RelInstitutionApplications")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_relInstApp_Applications");

                    b.HasOne("API.Models.Contact", "Contact")
                        .WithMany("RelInstitutionApplications")
                        .HasForeignKey("ContactId")
                        .IsRequired()
                        .HasConstraintName("FK_relInstApp_Contacts");

                    b.HasOne("API.Models.Discipline", "Discipline")
                        .WithMany("RelInstitutionApplications")
                        .HasForeignKey("DisciplineId")
                        .IsRequired()
                        .HasConstraintName("FK_relInstApp_Disciplines");

                    b.Navigation("Application");

                    b.Navigation("Contact");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("API.Models.RelInstitutionApplicationSubject", b =>
                {
                    b.HasOne("API.Models.RelInstitutionApplication", "InstitutionApplication")
                        .WithMany("RelInstitutionApplicationSubjects")
                        .HasForeignKey("InstitutionApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_relInstAppSubj_relInstApp");

                    b.HasOne("API.Models.Subject", "Subject")
                        .WithMany("RelInstitutionApplicationSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_relInstAppSubj_Subjects");

                    b.Navigation("InstitutionApplication");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("API.Models.Student", b =>
                {
                    b.HasOne("API.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("API.Models.Student", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Students_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Subject", b =>
                {
                    b.HasOne("API.Models.Faculty", "InstitutionFaculty")
                        .WithMany("Subjects")
                        .HasForeignKey("InstitutionFacultyId")
                        .HasConstraintName("FK_Subjects_Faculties");

                    b.Navigation("InstitutionFaculty");
                });

            modelBuilder.Entity("API.Models.WorkExperience", b =>
                {
                    b.HasOne("API.Models.Application", "Application")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_WorkExperiences_Applications");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("API.Models.Application", b =>
                {
                    b.Navigation("ApplicationDocument");

                    b.Navigation("RelInstitutionApplications");

                    b.Navigation("WorkExperiences");
                });

            modelBuilder.Entity("API.Models.Contact", b =>
                {
                    b.Navigation("RelInstitutionApplications");
                });

            modelBuilder.Entity("API.Models.Discipline", b =>
                {
                    b.Navigation("RelDisciplineSubjects");

                    b.Navigation("RelInstitutionApplications");
                });

            modelBuilder.Entity("API.Models.Faculty", b =>
                {
                    b.Navigation("Disciplines");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("API.Models.Institution", b =>
                {
                    b.Navigation("ApplicationReceivingInstitutionNavigations");

                    b.Navigation("ApplicationSendingInstitutionNavigations");

                    b.Navigation("Contacts");

                    b.Navigation("Faculties");
                });

            modelBuilder.Entity("API.Models.RelInstitutionApplication", b =>
                {
                    b.Navigation("RelInstitutionApplicationSubjects");
                });

            modelBuilder.Entity("API.Models.Student", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("LanguageCompetencies");
                });

            modelBuilder.Entity("API.Models.Subject", b =>
                {
                    b.Navigation("RelDisciplineSubjects");

                    b.Navigation("RelInstitutionApplicationSubjects");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Navigation("HashedTokens");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
